name: Flatpak Build

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  # Note: Flatpak build disabled on PRs because files don't exist in master yet
  # pull_request:
  #   branches: [ master, main ]

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: pv.flatpak
        manifest-path: com.github.SeanTater.pv.yml
        cache-key: flatpak-builder-${{ github.sha }}
        
    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: pv-flatpak-${{ github.sha }}
        path: pv.flatpak
        retention-days: 30

  # Only publish to Flathub on tagged releases
  publish:
    name: Publish to Flathub
    needs: flatpak
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download Flatpak Bundle
      uses: actions/download-artifact@v4
      with:
        name: pv-flatpak-${{ github.sha }}
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: pv.flatpak
        name: Release ${{ github.ref_name }}
        body: |
          ## Installation
          
          ### Flatpak
          Download the `pv.flatpak` file and install with:
          ```bash
          flatpak install pv.flatpak
          ```
          
          ### From Source
          ```bash
          cargo install --git https://github.com/SeanTater/pv.git --tag ${{ github.ref_name }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}