name: Release

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

  build-static:
    name: Build Static Binary
    runs-on: ubuntu-latest
    container: ghcr.io/rust-cross/rust-musl-cross:x86_64-musl
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build static binary
      run: |
        cargo build --release --target x86_64-unknown-linux-musl
        strip target/x86_64-unknown-linux-musl/release/pv

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: pv-linux-x86_64
        path: target/x86_64-unknown-linux-musl/release/pv
        retention-days: 30

  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: pv.flatpak
        manifest-path: com.github.SeanTater.pv.yml
        cache-key: flatpak-builder-${{ github.sha }}
        
    - name: Upload Flatpak Bundle
      uses: actions/upload-artifact@v4
      with:
        name: pv-flatpak-${{ github.sha }}
        path: pv.flatpak
        retention-days: 30

  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install toml-cli
      run: cargo install toml-cli

    - name: Verify version matches tag
      run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"

    - name: Publish to crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, build-static, flatpak, publish-crates]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download binary artifact
      uses: actions/download-artifact@v4
      with:
        name: pv-linux-x86_64
        path: ./artifacts

    - name: Download Flatpak artifact
      uses: actions/download-artifact@v4
      with:
        name: pv-flatpak-${{ github.sha }}
        path: ./artifacts

    - name: Rename binary for release
      run: |
        mv ./artifacts/pv ./artifacts/pv-linux-x86_64
        chmod +x ./artifacts/pv-linux-x86_64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./artifacts/pv-linux-x86_64
          ./artifacts/pv.flatpak
        name: Release ${{ github.ref_name }}
        body: |
          ## Installation

          ### Static Binary (Linux x86_64)
          Download the static binary and make it executable:
          ```bash
          curl -L -o pv https://github.com/SeanTater/pv/releases/download/${{ github.ref_name }}/pv-linux-x86_64
          chmod +x pv
          sudo mv pv /usr/local/bin/
          ```

          ### Flatpak
          Download the `pv.flatpak` file from the release assets and install with:
          ```bash
          curl -L -o pv.flatpak https://github.com/SeanTater/pv/releases/download/${{ github.ref_name }}/pv.flatpak
          flatpak install pv.flatpak
          ```

          ### From crates.io
          ```bash
          cargo install pv
          ```

          ### From Source
          ```bash
          cargo install --git https://github.com/SeanTater/pv.git --tag ${{ github.ref_name }}
          ```

          ## Verification
          Verify the installation:
          ```bash
          pv --version
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}